# MONGO | MYSQL
database: "mongo"
mongo:
  uri: ""
mysql:
  host: ""
  database: ""
  port: 3306
  auth:
    user: ""
    password: ""

# MODERN | LEGACY
# modern - supports hex colors (<red>, <green> etc).
# legacy - old style (&6, &5, &2 etc).
color-support: "modern"
islands-world: "islands"

spawn:
  world: "world"
  x: 0
  y: 100
  z: 0

first-island:
  x: 0
  y: 70
  z: 0
max-island-size: 100
island-radius: 100

islands:
  island-schematic: "island.schematic"
  multiple-selection: true
  inventory:
    title: "<red>Island Picker"
    size: 54
    overlay: false
    overlay-item: "WHITE_STAINED_GLASS_PANE"
  schematics:
    1:
      item: "GRASS_BLOCK"
      name: "<green>NORMAL Island"
      lore:
        - ""
        - "<white>Click to generate <green>NORMAL <white>island"
        - ""
      slot: 0
      schematic-file: "normal.schematic"
    2:
      item: "OBSIDIAN"
      name: "<red>NETHER Island"
      lore:
        - ""
        - "<white>Click to generate <red>NETHER <white>island"
        - ""
      slot: 1
      schematic-file: "normal.schematic"
    3:
      item: "END_PORTAL_FRAME"
      name: "<blue>END Island"
      lore:
        - ""
        - "<white>Click to generate <blue>END <white>island"
        - ""
      slot: 2
      schematic-file: "normal.schematic"

