# MONGO | MYSQL
database: "mongo"
mongo:
  uri: ""
mysql:
  host: ""
  database: ""
  port: 3306
  auth:
    user: ""
    password: ""

# MODERN | LEGACY
# modern - supports hex colors (<red>, <green> etc).
# legacy - old style (&6, &5, &2 etc).
color-support: "modern"

islands-world: "islands"

